In [13]:
import numpy as np
photos=np.ones([20,200,200,3])
import os
rootDir = 'photos'
for dirName, subdirList, fileList in os.walk(rootDir):
    print('Found directory: %s' % dirName)
    for fname in fileList:
        print('\t%s' % fname)
        print('Found directory: %s' % dirName)  
        
    
from PIL import Image
resize=(200,200)
for f in os.listdir('photos'):
    if f.endswith('.jpg'):
        i=Image.open(f)
        fn , fext = os.path.splitext(f)
        i.thumbnail((resize))
        i.save('resizeimg/{}_resizeimg{}'.format(fn,fext))

photos=np.array(i)
print(photos)
print(np.shape(i))

   

Found directory: photos
	1.jpg
Found directory: photos
	10.jpg
Found directory: photos
	11.jpg
Found directory: photos
	12.jpg
Found directory: photos
	13.jpg
Found directory: photos
	14.jpg
Found directory: photos
	15.jpg
Found directory: photos
	16.jpg
Found directory: photos
	17.jpg
Found directory: photos
	18.jpg
Found directory: photos
	19.jpg
Found directory: photos
	2.jpg
Found directory: photos
	20.jpg
Found directory: photos
	3.jpg
Found directory: photos
	4.jpg
Found directory: photos
	5.jpg
Found directory: photos
	6.jpg
Found directory: photos
	7.jpg
Found directory: photos
	8.jpg
Found directory: photos
	9.jpg
Found directory: photos
[[[209 128  75]
  [216 135  82]
  [208 127  74]
  ...
  [191 108  56]
  [194 118  64]
  [201 128  73]]

 [[214 133  80]
  [216 135  82]
  [210 129  76]
  ...
  [194 112  59]
  [197 121  67]
  [203 130  75]]

 [[221 140  87]
  [216 135  82]
  [212 131  78]
  ...
  [200 119  66]
  [203 127  73]
  [206 133  78]]

 ...

 [[ 21  20  38]
  [ 21  20 